//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quan_Ly_Nha_Hang.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETHD
    {
        public int IDHoaDon { get; set; }
        public int IDBan { get; set; }
        public int IDMon { get; set; }
        public int SoLuong { get; set; }
        public Nullable<double> DonGia { get; set; }
    
        public virtual BAN BAN { get; set; }
        public virtual HOADON HOADON { get; set; }
        public virtual MON MON { get; set; }
    }
}
