//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quan_Ly_Nha_Hang.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETMON
    {
        public int IDMon { get; set; }
        public int IDNguyenLieu { get; set; }
        public double Soluong { get; set; }
    
        public virtual MON MON { get; set; }
        public virtual NGUYENLIEU NGUYENLIEU { get; set; }
    }
}
