//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quan_Ly_Nha_Hang.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATBAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DATBAN()
        {
            this.CHITIETDB = new HashSet<CHITIETDB>();
        }
    
        public int IDDatBan { get; set; }
        public int IDKhachHang { get; set; }
        public System.TimeSpan GioBD { get; set; }
        public Nullable<System.DateTime> NgayDB { get; set; }
        public Nullable<int> SoluongBan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDB> CHITIETDB { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
    }
}
