//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quan_Ly_Nha_Hang.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOADON()
        {
            this.CHITIETHD = new HashSet<CHITIETHD>();
        }
    
        public int IDHoaDon { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public Nullable<double> ThanhTien { get; set; }
        public string PhuongThucTT { get; set; }
        public string TrangThaiTT { get; set; }
        public Nullable<System.DateTime> NgayThanhToan { get; set; }
        public int IDKhachHang { get; set; }
        public Nullable<int> IDKhuyenMai { get; set; }
        public Nullable<double> VAT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETHD> CHITIETHD { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual KHUYENMAI KHUYENMAI { get; set; }
    }
}
