//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quan_Ly_Nha_Hang.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHANCONG
    {
        public int IDNhanVien { get; set; }
        public int IDCaLamViec { get; set; }
        public int IDBan { get; set; }
        public System.DateTime NgayLV { get; set; }
        public string PhuTrachCV { get; set; }
    
        public virtual BAN BAN { get; set; }
        public virtual CALAMVIEC CALAMVIEC { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
