//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quan_Ly_Nha_Hang.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETDB
    {
        public int IDDatBan { get; set; }
        public int IDBan { get; set; }
        public string YeuCauDB { get; set; }
        public string Mota { get; set; }
    
        public virtual BAN BAN { get; set; }
        public virtual DATBAN DATBAN { get; set; }
    }
}
