//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIOHANG
    {
        public int MaGioHang { get; set; }
        public int MaKhachHang { get; set; }
        public int MaSanPham { get; set; }
        public int SoLuong { get; set; }
        public Nullable<double> TongTien { get; set; }
        public System.DateTime NgayThem { get; set; }
    
        public virtual SANPHAM SANPHAM { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
    }
}
