//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOADON()
        {
            this.CHITIETHDs = new HashSet<CHITIETHD>();
        }
    
        public int MaHoaDon { get; set; }
        public Nullable<int> MaKhachHang { get; set; }
        public Nullable<int> MaNhanVien { get; set; }
        public Nullable<System.DateTime> NgayDatHang { get; set; }
        public Nullable<int> TongTien { get; set; }
        public string TrangThaiDH { get; set; }
        public Nullable<int> MaKhuyenMai { get; set; }
        public Nullable<System.DateTime> TgianCapnhat { get; set; }
        public string PhuongThucTT { get; set; }
        public string TrangThaiTT { get; set; }
        public Nullable<System.DateTime> NgayTT { get; set; }
        public Nullable<System.DateTime> NgayDHDK { get; set; }
        public Nullable<System.DateTime> NgayGH { get; set; }
        public string GhiChu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETHD> CHITIETHDs { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual KHUYENMAI KHUYENMAI { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
